version: '3'
services:
  app:
    build: docker/php
    container_name: 5domikov-web
    volumes:
      - ./:/app
    depends_on:
      - db

  nginx:
    build: docker/nginx
    container_name: 5domikov-nginx
    ports:
      - "80:80"
    volumes:
      - ./:/app
    depends_on:
      - app

  db:
    container_name: 5domikov-postgres
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
